### ISSUE TITLE
Applications.commands scope on inviting

### ISSUE THREAD

**Issue by onerandomusername** [DisnakeDev/guide#16]
### Expands on

000-prerequisites/003-inviting-your-bot/

### Title

applications.commands scope

### Description

need this scope and why, what you can't do with it

### Additional context

can link to this from why won't my guild commands sync/ why are my guild commands hitting 403s?

### Would you like to implement this yourself?

No, I am only suggesting this addition.

**Comment by abhigyantrips** [comment]
As discussed in contributor chat, this already exists as a short note in `003-inviting-your-bot`. Going into any further detail on that page would be unnecessary, since the purpose of the scope has already been listed.
