### ISSUE TITLE
Typo in code sample for guide

### ISSUE THREAD

**Issue by minalike** [DisnakeDev/guide#36]
https://github.com/DisnakeDev/guide/blob/dc27302038a0010ee25240dcded8a6ce0499a76a/code-samples/getting-started/initial-files/main.py#L17-L18

I think line 18 should read `YOUR_BOT_TOKEN` without quotes, unless this is intentional; I see it's written with quotes in other code samples and throughout various guide pages.

**Comment by abhigyantrips** [comment]
Keeping `YOUR_BOT_TOKEN` in quotes is intentional, though I understand it's incorrect in this context. Will be fixed in the next major commit.

**Comment by minalike** [comment]
Since I'm going thru the guide, I'll update this comment with any typos I come across.

> thus we assume that there already exists a main.py file in your directory with initiates a commands.Bot() instance.
[which*](https://guide.disnake.dev/getting-started/using-cogs#creating-files)

**Comment by abhigyantrips** [comment]
Heya, apologies for leaving this unattended for so long. I'm currently committing changes to the site as per your latest comment.
