### ISSUE TITLE
Default theme for embedded discord message components is white regardless of the rest of the page's default theme.

### ISSUE THREAD

**Issue by elenakrittik** [DisnakeDev/guide#64]
https://github.com/DisnakeDev/guide/assets/77104725/521107b1-622e-4184-ad0b-251d8dd62178

**Comment by shiftinv** [comment]
oops, thanks for the report.
This regressed in https://github.com/DisnakeDev/guide/commit/9f607c5c4f01017ee97124e043690632acbec6da, and appears to be a bug in React hydration which only happens in production SSR builds, which is probably why I didn't catch it back then.
