### ISSUE TITLE
Classes Tutorial

### ISSUE THREAD

**Issue by OseSem** [DisnakeDev/guide#66]
### Expands on

guide.disnake.dev/getting-started/*

### Title

Tutorial For Classes

### Description

I will write a tutorial on how to use `commands.Bot` / `commands.InteractionBot` and the AutoSharded versions. I just need to know whether I should work on this, because if I make a PR right now and you guys don't like it I wasted my time.

### Would you like to implement this yourself?

Yes, I will be contributing this addition.

**Comment by shiftinv** [comment]
Thanks for the suggestion!
Two things here:
- There's currently still some overlap between the guide and some of the introductory sections in the docs, sometimes copied verbatim. It might make sense for us to resolve that first, which also then provides a better overview on what could be added/improved. No one's gotten around to actually doing that, unfortunately.
- It's not quite clear to me what these pages would contain - a very basic example for can already be found [here](https://docs.disnake.dev/en/stable/intro.html#basic-concepts), as well as numerous examples in the repository. Explaining classes/subclassing in a more general sense is better kept to the official python docs/guides, while going *much* more into detail probably doesn't provide much value compared to the complete [API Reference](https://docs.disnake.dev/en/stable/api/clients.html#disnake.Client) in the docs.

That being said, expanding the "Getting Started" pages of the guide a little bit in this direction could be useful. There hasn't been much demand for something like this in the past, so I would personally prefer to keep this on the back burner for now and come back to it once the docs/guide overlap is sorted out.

**Comment by OseSem** [comment]
That's fine, I will close this for now.
